# Example services.yaml entry

# Service ID
get_battery_status:
  # Gets the status of the battery for the target device. Because the blind has a
  # specific call for battery and because this does not advertise, nor give an actual %,
  # use this service instead to return true/false when battery is low
  name: "Get Battery Status"
  description: "Get the battery status for the Tuiss blinds selected"
  fields:
    entity_id:
      name: Entity Id
      description: Name of entitie(s) that should be checked.
      required: true
      selector:
        entity:
          integration: tuiss2ha
          domain: binary_sensor